apiVersion: v1
kind: PersistentVolume
metadata:
  name: efk-data-pv-0
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /spidermanefs/db/efk/data0
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efk-data-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efk-data-pv-1
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /spidermanefs/db/efk/data1
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efk-data-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efk-data-pv-2
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /spidermanefs/db/efk/data2
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efk-data-storage
