apiVersion: v1
kind: PersistentVolume
metadata:
  name: efk-master-pv-0
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /spidermanefs/db/efk/master0
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efk-master-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efk-master-pv-1
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /spidermanefs/db/efk/master1
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efk-master-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efk-master-pv-2
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /spidermanefs/db/efk/master2
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efk-master-storage
